services:
  deploy_registry:
    image: ${REGISTRY_HOST}/session-metrics
    build:
      context: ../src
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=session-metrics
      cache_to:
        - type=gha,scope=session-metrics,mode=max
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 7000:7000
    environment:
      OTEL_LOG_LEVEL: debug
      OTEL_TRACES_EXPORTER: console,otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel.next/
