source 'https://rubygems.org'

# todo ??
gem "rack-timeout"
gem "rack-attack"

gem 'async-io'
gem 'falcon'
gem 'sinatra'
gem "sequel"
gem "sqlite3"             # или  gem "pg" / "mysql2"  – выбери драйвер БД
gem "faraday"
gem 'faraday-retry',               '~> 2.2'
gem 'faraday-net_http_persistent', '~> 2.0'

gem 'rack'
gem 'rackup'
gem 'sequel'
gem 'sqlite3'

gem "prometheus-client"
gem 'stack-service-base'

group :development do
  gem 'rubocop'
end